### ISSUE TITLE
Add cime_config directory into FV3 and NEMS

### ISSUE THREAD

**Issue by mvertens** [ufs-community/ufs-mrweather-app#14]
In order for the UFS weather model to be cime compliant - a top level cime_config/ directory needs to be added. We have this in a separate FV3_interface repositories as externals - but this adds complexity to the system that will cause problems moving forwards. See:
https://github.com/ESCOMP/NEMS_interface and https://github.com/ESCOMP/FV3GFS_interface
There will be two forthcoming PRs for this issue.

**Comment by jedwards4b** [comment]
To whom should the NEMS and FV3 PR's be assigned?

**Comment by junwang-noaa** [comment]
The general practice at EMC is not to add workflow related code changes into model source code, workflow required code will stay at the workflow repo because the workflow used in operational could be different from the workflow used for development. Since the public release will not used by operation implementation at this time, it's OK to make pull request to public release branch. To make pull requests to public release branch, please go to:
https://github.com/NOAA-EMC/NEMS
https://github.com/NOAA-EMC/fv3atm
to make pull request to ufs_public_release branch.  Code managers (RatkoVasic-NOAA/ for NEMS and DusanJovic-NOAA for fv3atm) will schedule a commit.

**Comment by DusanJovic-NOAA** [comment]
This directory does not belong to this repository. It's workflow specific and as such should be part of either workflow or app repository.

**Comment by mvertens** [comment]
Closing this issue for now. We will proceed with using interface repositories.
