### ISSUE TITLE
NCEPlibs superproject needs to point to UPP ufs_public_release branch

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-mrweather-app#27]

**Comment by mark-a-potts** [comment]
Put in a pull request to get cmake build files into ufs_public_release branch from my ufs_release_v1.0 branch.

**Comment by arunchawla-NOAA** [comment]
@WenMeng-NOAA what is the status of this PR ?

**Comment by fossell** [comment]
@arunchawla-NOAA @WenMeng-NOAA  The DTC has just finished up testing of the community build modifications and will be merge those into ufs_public_release branch likely today.  Then we will look at the cmake PR from @mark-a-potts and merge that as well. So should be ready to point to that branch and start testing UPP within the app by end of the week.  It's my understanding that these cmake mods are intended for building inline post as a library, but from previous discussions I thought the release was not going to use inline post? Rather, users were going to be expected to build UPP as a pre-req standalone utility. Please correct any misunderstanding I may have.

**Comment by WenMeng-NOAA** [comment]
@fossell For my understanding, the PR is enable the NCEPLIBS superproject build, not for in-line post.

**Comment by arunchawla-NOAA** [comment]
That is right. This is not for in line post but to use with nceplibs super
project which uses the cmake build. Thanks !
---------------------------------------------------------------
Arun Chawla
Chief
Engineering & Implementation Branch
Room 2083
National Center for Weather & Climate Prediction
5830 University Research Court
College Park, MD 20740
Ph: 301-683-3740
Fx: 301-683-3703
------------------------------------------------------------

**Comment by fossell** [comment]
@arunchawla-NOAA @WenMeng-NOAA Thanks for the clarification. I will update this thread when the cmake PR changes from @mark-a-potts are merged into ufs_public_release so this PR can be resolved and superproject can point to that branch.

**Comment by arunchawla-NOAA** [comment]
@fossell and @WenMeng-NOAA what is the status of this PR from @mark-a-potts . Please tag up with @climbfuji and @kgerheiser so that they can update the NCEPLIBS super project to point to the UPP release branch at that point

**Comment by fossell** [comment]
@arunchawla-NOAA @climbfuji @mark-a-potts @kgerheiser  DTC will have a branch and status update very soon.

**Comment by fossell** [comment]
@arunchawla-NOAA @climbfuji @mark-a-potts @kgerheiser -- UPP branch has been updated to incorporate cmake mods requested for ufs.  Note that there are now two branches in EMC_post repo for ufs due to previous overlap in efforts.  They are called ufs_release_v1.0 and ufs_public_release. Those branches are now mostly identical with deltas only due to extra documentation rst files that DTC has been working for with UFS documentation team that reside in ufs_public_release.  @arunchawla-NOAA Please advise on what the official naming convention should be for this branch.  I can remove the other and ensure the documentation is in the proper branch to avoid confusion with multiple branches.  Then NCEPLIBS can point to that branch.

Also, these ufs* branches do not yet include the new community build structure that DTC is working on. There was a runtime problem in our tests when we merged the cmake mods and develop branches so we're investigating that now.  My preference is that we try to get this new build structure into ufs branch eventually before release, even if nothing is used from it for ufs, but just so that the directory trees look the same to community end users whether they are using the ufs app or a standalone version of UPP.  

The ufs teams can use the EMC_post ufs branch now to test and keep things moving on their end, and we'll continue to work on the runtime issues on our end and hopefully merge in community build structure mods (with ufs team approvals first, though they shouldn't impact ufs) into the authoritative EMC_post release branch prior to UFS release and code freeze.  @arunchawla-NOAA Does this sound reasonable to you?

**Comment by climbfuji** [comment]
@fossell For all other NCEPLIBS-* submodules of the NCEPLIBS umbrella build, the branch is called ufs_release_v1.0 - would be good to use the same for consistency. When you say 

> The ufs teams can use the EMC_post ufs branch

you mean the `ufs_release_v1.0` or `ufs_public_release` branch? I understand that the differences are only documentation (which should be merged from `ufs_public_release` into `ufs_release_v1.0` if the latter will be used). Thanks!

**Comment by fossell** [comment]
Thanks @climbfuji.  We will use ufs_release_v1.0 branch then.  I will merge documentation files into that branch.  When I said:
> The ufs teams can use the EMC_post ufs branch

I meant either ufs_release_v1.0 or ufs_public_release, whatever was decided to be the authoritative name.  So from here on out we will just use ufs_release_v1.0.

**Comment by ceceliadid** [comment]
Just to note, I don't think the term UFS release v1.0 is going to be used anywhere else in referring to the release. My understanding is that there was a decision to not use this in any announcements and to only call the release the medium range application v1.

**Comment by arunchawla-NOAA** [comment]
@climbfuji and @mark-a-potts once you have confirmed that NCEPLIBS super project points to the correct branch for UPP release and builds please close this ticket

**Comment by climbfuji** [comment]
With PR https://github.com/NOAA-EMC/NCEPLIBS/pull/12 to the NCEPLIBS umbrella build, all repositories use the branch names ufs_release_1.0 (except UFS_UTILS, which uses release/ufs_release_1.0; see https://github.com/NOAA-EMC/UFS_UTILS/issues/42), and the umbrella build points to the correct branches for all submodules.
