### ISSUE TITLE
NCEPLIBS: cleanup work

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-mrweather-app#47]
We need to clean up the NCEPLIBS build (individual NCEPLIBS-* repositories) to
- remove old gmake build scripts and any other unnecessary configuration/documentation that may lead to confusion
- check for build procedures (preprocessing .F90->.f90, ...) and file names that are incompatible with the case-preserving but not case-sensitive filesystem on macOS

**Comment by arunchawla-NOAA** [comment]
@climbfuji close this if it is done or label it post release

**Comment by climbfuji** [comment]
I think this will need to be post release.

**Comment by Hang-Lei-NOAA** [comment]
I have merged the ufs_release_v1.0 with develop on Hera. After the access
to hera back.  All will be pushed to github and tag. Old tags have been
agreed to be removed on NCEPLIBS meeting. It will be done as well.

**Comment by arunchawla-NOAA** [comment]
Does this mean that you will have tags for all the libraries from the
master branch of github? The umbrella builds will then have to point to
these tags. Just want to make sure
---------------------------------------------------------------
Arun Chawla
Chief
Engineering & Implementation Branch
Room 2083
National Center for Weather & Climate Prediction
5830 University Research Court
College Park, MD 20740
Phone : 301-683-3740
Mobile : 240-564-5675
     Fax : 301-683-3703
------------------------------------------------------------

**Comment by Hang-Lei-NOAA** [comment]
Yes,
but the ufs_release_v1.0 branch will be kept util the removal is agreed by
all.

**Comment by Hang-Lei-NOAA** [comment]
(1) According to the latest update, the  release/public-v1 branch is
merged into develop, and then merged into master branch. New tags have been
made for all public release NCEPLIB libraries and ready to use.
(2) Since some feature branches are still in use, I have asked each
code-manager to confirm with owner and remove them as necessary as it is. I
also contacted the github official company. They are developing an
upgrading, which will allow users just pick several tags for releases. We
decided to wait for this function come up.
Thanks to the work from all of you.
This ticket can be closed.
